name: 'GitHub Actions DZqiandao Bot'
# UTC17:00(北京UTC+8 01:00点)触发任务
on:
  push:
  schedule:
    - cron: '0 16 * * *'

jobs:
  curl-discuz:
     runs-on: ubuntu-latest
     steps:
       - name: 'xecute command'
         env:
          USER_AGENT: ${{ secrets.USER_AGENT }}
          #Token用于识别登录状态与身份
          X_LITEMALL_TOKEN: ${{ secrets.X_LITEMALL_TOKEN }}
         # 向站点发送 GET 请求
         run:                                 
          curl -X GET  -A "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 NetType/WIFI MicroMessenger/7.0.20.1781(0x6700143B) WindowsWechat(0x63040026)" -H "Content-Type:application/json;charset=UTF-8" "https://youthstudy.12355.net/saomah5/api/young/mark/add?X-Litemall-IdentiFication=young&X-Litemall-Token=$X_LITEMALL_TOKEN"
